### ISSUE TITLE
Won't compile on Ubuntu 25.04

### ISSUE THREAD

**Issue by mikemocha** [sarah-walker-pcem/arculator#60]
Trying to compile per the readme on a stock Ubuntu 25.04 system. Is there some issue with how libraries are being declared? I tried poking around sound_sdl2.c moving include statements around, not helping. Any thoughts? Thanks.

> g++ -DPACKAGE_NAME=\"Arculator\" -DPACKAGE_TARNAME=\"arculator\" -DPACKAGE_VERSION=\"v2.2\" -DPACKAGE_STRING=\"Arculator\ v2.2\" -DPACKAGE_BUGREPORT=\"Sarah\ Walker\ \<b-em@bbcmicro.com\>\" -DPACKAGE_URL=\"\" -DPACKAGE=\"arculator\" -DVERSION=\"v2.2\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBZ=1 -DHAVE_LIBPTHREAD=1 -DHAVE_LIBASOUND=1 -I.    -I/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.2 -I/usr/include/wx-3.2 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -I/usr/include/SDL2 -D_REENTRANT -O3  -DRELEASE_BUILD -g -O2 -MT arculator-wx-console.o -MD -MP -MF .deps/arculator-wx-console.Tpo -c -o arculator-wx-console.o `test -f 'wx-console.cc' || echo './'`wx-console.cc
> 
> sound_sdl2.c: In function ‘sound_dev_init’:
> sound_sdl2.c:23:9: error: implicit declaration of function ‘rpclog’ [-Wimplicit-function-declaration]
>    23 |         rpclog("audio_device=%u\n", audio_device);
>       |         ^~~~~~
> make[1]: *** [Makefile:1352: arculator-sound_sdl2.o] Error 1

**Comment by filiperinaldi** [comment]
Your logs don't seem to make sense unless you are using parallel builds as g++ command above does not match the file that fails to compile.

The error says rpclog was not known to sound_sdl2.c. rpclog seems to be defined in arc.h. There is a patch that seems to fix this exact issue: https://github.com/sarah-walker-pcem/arculator/commit/261e958763bf2b01fac29cef2ad0c402b4cfd4b0

Perhaps you have a copy of the project before that patch was available?
